apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-server
  namespace: drawspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-server
  template:
    metadata:
      labels:
        app: ws-server
    spec:
      containers:
        - name: ws-server
          image: ghcr.io/tripurari-singh/excalidraw-ws-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: drawspace-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: drawspace-secrets
                  key: JWT_SECRET
