apiVersion: v1
kind: Secret
metadata:
  name: drawspace-secrets
  namespace: drawspace
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/drawspace"
  JWT_SECRET: "drawspace-super-secret-key-2024"
  POSTGRES_PASSWORD: "postgres"
